### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nschucky** [cemolcay/TransitionManager#6]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by cemolcay** [comment]
I'd appreciate if you could send me a pull request.

**Comment by nschucky** [comment]
i did the update, can you create a branch called swift3 in the project?

**Comment by cemolcay** [comment]
https://github.com/cemolcay/TransitionManager/tree/swift3
